/// One row per day from 1 January 2010 to 31 October 2019, contiguous, and marked as
/// the date table so DATEADD and TOTALYTD have a calendar to walk.
///
/// 'In Like For Like Period' is the column that keeps 2019 honest. The file stops on
/// 31 October, so 2019 holds ten months. A year-on-year chart that ignores that shows
/// a 17% collapse in 2019 which is entirely the calendar; the like-for-like measures
/// filter on this column and compare January to October against January to October.
table Date
	lineageTag: c640a452-5a21-5bfd-8707-28a5c079d74a
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: d mmm yyyy
		lineageTag: ebc99104-8890-5314-a965-9512580e8279
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 26c52ba2-5602-562b-acfb-2cbb046f7620
		summarizeBy: none
		sourceColumn: Year

	column Quarter
		dataType: string
		lineageTag: 87a37d8e-dcee-54e4-89ae-2978dee14069
		summarizeBy: none
		sourceColumn: Quarter

	column 'Quarter Year'
		dataType: string
		lineageTag: 1f44472b-a003-50ce-9317-21dc07417048
		summarizeBy: none
		sourceColumn: QuarterYear
		sortByColumn: 'Quarter Year Sort'

	column 'Quarter Year Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 87cd21eb-7156-5ac1-8774-6bbcaafe9dc9
		summarizeBy: none
		sourceColumn: QuarterYearSort

	column 'Month No'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 69a2ad5f-a613-5f81-ba1a-04500c047668
		summarizeBy: none
		sourceColumn: MonthNumber

	column Month
		dataType: string
		lineageTag: 7a4c11f5-5eef-5fab-b239-71aaf144b486
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Month No'

	column 'Month Short'
		dataType: string
		lineageTag: dc9e8139-848a-5cac-93fc-ad4b5a8a58fb
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: 'Month No'

	column 'Month Year'
		dataType: string
		lineageTag: 161c1308-623a-5ddd-966f-02c7798e6ac3
		summarizeBy: none
		sourceColumn: MonthYear
		sortByColumn: 'Month Year Sort'

	column 'Month Year Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f65d62ed-e4bb-5f6f-8046-c2e299853444
		summarizeBy: none
		sourceColumn: MonthYearSort

	/// First day of the month. Visible because the ten-year trend charts put it
	/// on a continuous axis - 118 month-year strings would not fit.
	column 'Month Start'
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: f77f75b8-41c4-5769-8316-99e647a4f269
		summarizeBy: none
		sourceColumn: MonthStart

	column 'Day of Week'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 969e6e54-e2a2-538b-89ab-042ad0423e2d
		summarizeBy: none
		sourceColumn: DayOfWeek

	column Day
		dataType: string
		lineageTag: b804c682-161e-57f6-af5e-258abc2b453b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: 'Day of Week'

	column 'Is Weekend'
		dataType: string
		lineageTag: b98008a6-d165-5fd0-9b9d-5bf599b955b6
		summarizeBy: none
		sourceColumn: IsWeekend

	/// Yes for January to October, the months every year in the file has.
	column 'In Like For Like Period'
		dataType: string
		lineageTag: ae36dbaf-079e-5065-acf3-3a9c7bd08370
		summarizeBy: none
		sourceColumn: InLikeForLikePeriod

	/// No for 2019, which stops on 31 October.
	column 'Is Complete Year'
		dataType: string
		lineageTag: 99cce892-2c09-5aa6-91ae-ee09d3bbb5df
		summarizeBy: none
		sourceColumn: IsCompleteYear

	column 'Cal Year' = YEAR('Date'[Date])
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 9a847582-9b3e-5bbb-8261-b197b9a3a2be
		summarizeBy: none

	column 'Cal Month No' = MONTH('Date'[Date])
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: f582dd3f-0fad-52ac-a7d9-8ca14f0dc57a
		summarizeBy: none

	/// Month name, January to December.
	column 'Cal Month' = FORMAT('Date'[Date], "mmmm")
		dataType: string
		displayFolder: Calendar
		lineageTag: 45698ab1-2a33-554e-9f25-b164d6e6f7c3
		summarizeBy: none
		sortByColumn: 'Cal Month No'

	column 'Cal Month Short' = FORMAT('Date'[Date], "mmm")
		dataType: string
		displayFolder: Calendar
		lineageTag: 33d763b0-7c0e-5bf8-b8e9-aa2b861bc799
		summarizeBy: none
		sortByColumn: 'Cal Month No'

	column 'Cal Quarter' = "Q" & ROUNDUP(MONTH('Date'[Date]) / 3, 0)
		dataType: string
		displayFolder: Calendar
		lineageTag: 4cc9f392-534d-58cf-b230-adf313781a55
		summarizeBy: none

	column 'Cal Quarter Key' = YEAR('Date'[Date]) * 10 + ROUNDUP(MONTH('Date'[Date]) / 3, 0)
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: d574323f-cfe9-59aa-b856-e0124a8189a0
		summarizeBy: none

	column 'Cal Quarter Label' = "Q" & ROUNDUP(MONTH('Date'[Date]) / 3, 0) & " " & YEAR('Date'[Date])
		dataType: string
		displayFolder: Calendar
		lineageTag: bc1cc892-16f2-5707-8b1e-736c50c2b3f0
		summarizeBy: none
		sortByColumn: 'Cal Quarter Key'

	column 'Cal Month in Quarter No' = MOD(MONTH('Date'[Date]) - 1, 3) + 1
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: e367309d-7be2-5c21-b415-f4638f29f16d
		summarizeBy: none

	/// The Month view's column headers.
	column 'Cal Month in Quarter' = SWITCH(MOD(MONTH('Date'[Date]) - 1, 3) + 1, 1, "1st month", 2, "2nd month", "3rd month")
		dataType: string
		displayFolder: Calendar
		lineageTag: a9453da7-9fb6-5dd9-9126-e140a27a6ac9
		summarizeBy: none
		sortByColumn: 'Cal Month in Quarter No'

	/// Monday = 1.
	column 'Cal Weekday No' = WEEKDAY('Date'[Date], 2)
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 2c050e32-faa1-52ce-8292-825febbef228
		summarizeBy: none

	/// Mon to Sun, in that order - the Day view's column headers.
	column 'Cal Day Short' = FORMAT('Date'[Date], "ddd")
		dataType: string
		displayFolder: Calendar
		lineageTag: 06ae0bd9-2d8c-53bb-8f74-94c6f2b2b844
		summarizeBy: none
		sortByColumn: 'Cal Weekday No'

	column 'Cal Day Name' = FORMAT('Date'[Date], "dddd")
		dataType: string
		displayFolder: Calendar
		lineageTag: 9e5f3573-21a5-5b54-a205-5692a411a3aa
		summarizeBy: none
		sortByColumn: 'Cal Weekday No'

	/// Which row of a Monday-first month grid the day sits on: 1 to 6.
	column 'Cal Week of Month' = INT((DAY('Date'[Date]) + WEEKDAY(DATE(YEAR('Date'[Date]), MONTH('Date'[Date]), 1), 2) - 2) / 7) + 1
		dataType: int64
		formatString: 0
		displayFolder: Calendar
		lineageTag: 0eded621-bb6b-5fce-8639-97f74fb33bad
		summarizeBy: none

	column 'Cal Week Row' = REPT(UNICHAR(8203), INT((DAY('Date'[Date]) + WEEKDAY(DATE(YEAR('Date'[Date]), MONTH('Date'[Date]), 1), 2) - 2) / 7) + 1)
		dataType: string
		displayFolder: Calendar
		lineageTag: 07cac5d0-d694-5d1b-b1a5-174cca4dfecb
		summarizeBy: none
		sortByColumn: 'Cal Week of Month'

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/owilliams84/powerbi-card-transactions/main/data/dim_date.csv"), [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Applied Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"Date", type date}, {"Year", Int64.Type}, {"Quarter", type text}, {"QuarterYear", type text}, {"QuarterYearSort", Int64.Type}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"MonthShort", type text}, {"MonthYear", type text}, {"MonthYearSort", Int64.Type}, {"MonthStart", type date}, {"DayOfWeek", Int64.Type}, {"DayName", type text}, {"IsWeekend", type text}, {"InLikeForLikePeriod", type text}, {"IsCompleteYear", type text}})
				in
				    #"Applied Types"

	annotation PBI_ResultType = Table
