/// Confirmed fraud, confirmed not fraud, or not labelled - three states, not two.
///
/// The source's fraud labels cover 67% of transactions and no more; the rest are
/// simply unlabelled. Treating an unlabelled row as clean is the single easiest way
/// to get this dataset wrong, and it understates the fraud rate by a third. Every
/// fraud measure in this model divides by labelled rows only, and the report shows
/// the naive figure beside it so the gap is visible rather than assumed away.
table 'Fraud Status'
	lineageTag: ad2d0230-b0f3-5ac3-8839-6f39e56d6b5f

	column 'Fraud Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: e31f9ec1-9798-5513-bada-a31728875123
		summarizeBy: none
		sourceColumn: FraudKey

	column 'Fraud Status'
		dataType: string
		lineageTag: 380486b0-ee7a-5db3-b637-a3e955fe1ebc
		summarizeBy: none
		sourceColumn: FraudStatus
		sortByColumn: 'Fraud Sort'

	column 'Fraud Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e88688e4-f90b-5264-9b78-e0c0cc422ee2
		summarizeBy: none
		sourceColumn: FraudSort

	column 'Is Labelled'
		dataType: string
		lineageTag: b3f17354-b19c-54d3-bffc-d0b3986df12b
		summarizeBy: none
		sourceColumn: IsLabelled

	column 'Is Fraud'
		dataType: string
		lineageTag: b60b6eb3-4b6e-51eb-90fe-c16576862017
		summarizeBy: none
		sourceColumn: IsFraud

	partition 'Fraud Status' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\\Users\\OmarWilliams\\OneDrive - MILESTONEBI\\Projects\\Claude Projects\\ClaudeCode\\Card-Transactions-Fraud\\data\\dim_fraud_status.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Applied Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"FraudKey", Int64.Type}, {"FraudStatus", type text}, {"FraudSort", Int64.Type}, {"IsLabelled", type text}, {"IsFraud", type text}})
				in
				    #"Applied Types"

	annotation PBI_ResultType = Table
